import { Assets, type Spritesheet, type Texture } from 'pixi.js';

/**
 * Self-made pixel art for the style test, generated by scripts/build-sprites.ts from art/pixel/.
 * Everything is sampled nearest-neighbour so pixels stay crisp at integer zoom.
 */
export interface PixelAssets {
  sheet: Spritesheet;
  ground: { sand: Texture; wetSand: Texture; water: Texture; shore: Texture; tide: Texture };
}

export async function loadPixelAssets(): Promise<PixelAssets> {
  const base = `${import.meta.env.BASE_URL}assets/sprites/`;
  const nearest = { scaleMode: 'nearest' as const };
  const tile = (name: string): Promise<Texture> =>
    Assets.load<Texture>({ src: `${base}ground-${name}.png`, data: { ...nearest, addressMode: 'repeat' } });
  const [sheet, sand, wetSand, water, shore, tide] = await Promise.all([
    Assets.load<Spritesheet>({ src: `${base}pixel.json`, data: { textureOptions: nearest } }),
    tile('sand'),
    tile('wet-sand'),
    tile('water'),
    tile('shore'),
    tile('tide'),
  ]);
  return { sheet, ground: { sand, wetSand, water, shore, tide } };
}

export function frames(assets: PixelAssets, key: string): Texture[] {
  const list = assets.sheet.animations[key];
  if (!list?.length) throw new Error(`Pixel animation missing: ${key}`);
  return list;
}
